info:
  contact: {}
  description: 一个匿名熬夜论坛
  title: 不眠夜
  version: "1.0"
paths:
  /login:
    post:
      consumes:
      - application/json
      description: Logs in a registered user.
      parameters:
      - description: User email
        in: formData
        name: email
        required: true
        type: string
      - description: User password
        in: formData
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "302":
          description: 登陆成功
          schema:
            type: string
        "400":
          description: 无法解析的表单数据" or "该邮箱还未注册" or "密码错误
          schema:
            type: string
        "500":
          description: 服务器创建会话失败
          schema:
            type: string
      summary: User login
swagger: "2.0"
